# This workflow releases a new chart version when PRs are merged to main branch if:
# - there are any changes under charts/trino directory
# - no existing release for the chart version exists
name: Release Trino Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/trino/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup node
        uses: AutoModality/action-clean@1.1.0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release Changelog Builder
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: '.github/changelog-config.json'
          outputFile: ${{ runner.temp }}/CHANGELOG.md
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NOTES_FILE: ${{ runner.temp }}/CHANGELOG.md
          # If we didn't bump the chart version then we can skip the release
          CR_SKIP_EXISTING: true
