name: Sync Readme

on:
  push:
    branches:
      - main
    paths:
      - '**/README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Configure git user and email
        run: |
          git config user.name "GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy all README files from main to gh-pages
        run: |
          cd main
          # cp --parents preserves directory structure
          find . -name 'README.md' -exec cp --parents '{}' "../gh-pages/" ';'
      - name: Commit changes to gh-pages and push
        run: |
          cd gh-pages
          git add .
          git commit --signoff -m "Sync READMEs from main"
          git push
